<a href="https://colab.research.google.com/github/mahinsagotra/3rd-SEM-Project/blob/master/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello')

Hello


In [ ]:
import numpy as np

a = np.array(['Hello','World'])
print(a)
a = np.append(a,'i')
print('Current array: {}'.format(a))
print('Printing each Element')
for i in a:
  print(i)
print('\nPrinting each element and their index')
for i,e in enumerate(a):
  print('Index: {}, was: {}'.format(i,e))

['Hello' 'World']
Current array: ['Hello' 'World' 'i']
Printing each Element
Hello
World
i

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: i


In [ ]:
print('\nShowing some basic math on arrays')
b = np.array([0,1,4,3,2])
print('Max: {}'.format(np.max(b)))
print('Average: {}'.format(np.average(b)))
print('Max Index: {}'.format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max Index: 2


In [ ]:
print('\nYou can print the type of anything')
print('Type of b: {}, type of b[0]: {}'.format(type(b), type(a[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.str_'>


In [ ]:
print('\nUse numpy to create a [3,3] dimension array with random number')
c = np.random.rand(3,3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.47432852 0.05174104 0.74674538]
 [0.41178452 0.43312349 0.47670336]
 [0.35784562 0.27914656 0.97589775]]


In [ ]:
print('\nYou can print the dimension of arrays')
print('Shape of a: {}'.format(a.shape))
print('Shape of b: {}'.format(b.shape))
print('Shape of c: {}'.format(c.shape))


You can print the dimension of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


In [ ]:
!pip install numpy

In [ ]:
!ls -l
!pwd

total 4
drwxr-xr-x 1 root root 4096 Oct  8 13:45 sample_data
/content
